'use client';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ApolloProvider } from '@apollo/client';
import { client } from '../lib/apollo-client';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ApolloProvider client={client}>
        <AntdRegistry>{children}</AntdRegistry>
      </ApolloProvider>
    </body>
  </html>
);

export default RootLayout;
